### ISSUE TITLE
wronge card title in entries

### ISSUE THREAD

**Issue by mahdisayeri** [Vistaroid/Moodino#102]
i enter 3 entry in 1401/2/10 
and enter 1 in 1400/2/11

<img width="286" alt="Screenshot 2022-05-01 091422" src="https://user-images.githubusercontent.com/45222547/166132547-0ccd69e9-35dc-4bf8-bb8f-9f9aae4540eb.png">

**Comment by mrkhoshneshin** [comment]
Fixed
