### ISSUE TITLE
bottom navigation bug

### ISSUE THREAD

**Issue by mrkhoshneshin** [Vistaroid/Moodino#68]
when you are in add entry fragment and wanna add picture, suddenly bottom navigation appear (some times happen)

![photo_2022-04-13_10-02-04](https://user-images.githubusercontent.com/77789426/163232643-49e021e6-4f16-4c52-ad0b-22842eaf9bf2.jpg)

**Comment by Tayeb-shahbakhsh** [comment]
hmmm I tested it but I did not see this bug yet !

**Comment by Tayeb-shahbakhsh** [comment]
issue is resolved, now bottom navigation only show on 4 main fragments.
